/* Panorama Docente — módulo de ajustes de Alumnos
   Mantiene el núcleo intacto: agrega eliminación con confirmación y evita duplicados en importaciones.
*/
(function(){
  const KEY='panoramaDocente_v1';
  const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase().replace(/\s+/g,' ');
  function read(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}}
  function write(db){localStorage.setItem(KEY,JSON.stringify(db))}
  function deleteStudent(id){const db=read();if(!db||!Array.isArray(db.students))return;const s=db.students.find(x=>x.id===id);if(!s)return;if(!confirm(`¿Eliminar al alumno “${s.name}”?\n\nEsta acción eliminará también sus asistencias, calificaciones e incidencias asociadas.`))return;db.students=db.students.filter(x=>x.id!==id);db.attendance=(db.attendance||[]).filter(x=>x.studentId!==id);db.grades=(db.grades||[]).filter(x=>x.studentId!==id);db.incidents=(db.incidents||[]).filter(x=>x.studentId!==id);write(db);location.reload()}
  function addDeleteButtons(){if(!location.pathname)return;const rows=document.querySelectorAll('#studentRows tr');rows.forEach(row=>{if(row.querySelector('.pd-delete-student'))return;const edit=row.querySelector('button[onclick*="openStudentModal"]');if(!edit)return;const m=(edit.getAttribute('onclick')||'').match(/openStudentModal\('([^']+)'\)/);if(!m)return;const b=document.createElement('button');b.className='btn danger pd-delete-student';b.textContent='Eliminar';b.type='button';b.onclick=()=>deleteStudent(m[1]);edit.parentElement.appendChild(document.createTextNode(' '));edit.parentElement.appendChild(b)})}
  function importExcel(){const f=document.getElementById('xlsxFile')?.files?.[0];if(!f)return alert('Selecciona un archivo.');const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const db=read();if(!db)return alert('No se encontraron datos locales.');const existing=new Set((db.students||[]).map(s=>`${normalize(s.name)}|${normalize(s.curp)}|${normalize(s.groupId)}`));let added=0,duplicates=0;rows.forEach(row=>{const keys=Object.keys(row).map(k=>[k,k.toLowerCase().trim()]);const get=(...names)=>{const k=keys.find(([a,b])=>names.includes(b));return k?row[k[0]]:''};let name=get('nombre completo','nombre');if(!name)name=[get('apellido paterno','paterno'),get('apellido materno','materno'),get('nombres')].filter(Boolean).join(' ');let raw=String(get('grupo')||'').toUpperCase().replace('º','').replace(' ','');let grade=raw.match(/[123]/)?.[0]||'1',letter=raw.match(/[ABCDE]/)?.[0]||'A',groupId=grade+letter;if(!db.groups.some(g=>g.id===groupId))groupId='1A';const curp=String(get('curp')||'').trim();if(!name)return;const exact=`${normalize(name)}|${normalize(curp)}|${normalize(groupId)}`;const sameNameGroup=`${normalize(name)}|${normalize(groupId)}`;const duplicate=existing.has(exact)||[...existing].some(k=>{const p=k.split('|');return p[0]===normalize(name)&&p[2]===normalize(groupId)});if(duplicate){duplicates++;return}db.students.push({id:'stu_'+Math.random().toString(36).slice(2,9),name:String(name).trim(),curp,groupId});existing.add(exact);added++});write(db);alert(`Importación terminada.\n\nAgregados: ${added}\nDuplicados omitidos: ${duplicates}`);location.reload()}catch(err){alert('No se pudo leer el archivo: '+err.message)}};r.readAsArrayBuffer(f)}
  window.PD_ALUMNOS={deleteStudent,addDeleteButtons};
  window.importExcel=importExcel;
  const observer=new MutationObserver(addDeleteButtons);
  observer.observe(document.getElementById('content')||document.body,{childList:true,subtree:true});
  addDeleteButtons();
})();
