/* Panorama Docente — módulo de Reportes */
(function(){
  const esc3=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const pct=n=>Number.isFinite(n)?`${n.toFixed(1)}%`:'—';
  const avg=xs=>{const a=xs.map(Number).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null};
  const studentsOf=g=>db.students.filter(s=>s.groupId===g);
  const attendanceOf=(sid,from,to)=>db.attendance.filter(a=>a.studentId===sid&&(!from||a.date>=from)&&(!to||a.date<=to));
  const studentAvg3=s=>avg(db.grades.filter(g=>g.studentId===s.id).map(g=>g.value));
  const studentAtt3=(s,from,to)=>{const a=attendanceOf(s.id,from,to);return a.length?(a.filter(x=>x.status==='P'||x.status==='R').length/a.length)*100:null};
  function renderReportes(){
    const active=db.groups.filter(g=>g.active);
    document.getElementById('content').innerHTML=`<div class="toolbar"><select id="pdRepGroup">${active.map(g=>`<option value="${g.id}">${esc3(g.name)}</option>`).join('')}</select><input id="pdRepFrom" type="date"><input id="pdRepTo" type="date" value="${today()}"><button class="btn primary" type="button" id="pdRepPreview">Actualizar</button><button class="btn" type="button" id="pdRepGroupPdf">PDF del grupo</button><button class="btn" type="button" id="pdRepExcel">Excel</button></div><div id="pdRepSummary"></div>`;
    document.getElementById('pdRepPreview').onclick=preview;
    document.getElementById('pdRepGroupPdf').onclick=groupPdf;
    document.getElementById('pdRepExcel').onclick=groupExcel;
    preview();
  }
  function getData(){const gid=document.getElementById('pdRepGroup').value,from=document.getElementById('pdRepFrom').value,to=document.getElementById('pdRepTo').value,students=studentsOf(gid);const grades=db.grades.filter(g=>students.some(s=>s.id===g.studentId));const att=db.attendance.filter(a=>a.groupId===gid&&(!from||a.date>=from)&&(!to||a.date<=to));return {gid,from,to,students,grades,att}};
  function preview(){const d=getData(),av=avg(d.grades.map(g=>g.value)),at=d.att.length?(d.att.filter(a=>a.status==='P'||a.status==='R').length/d.att.length)*100:null,inc=(db.incidents||[]).filter(i=>i.groupId===d.gid&&(!d.from||i.date>=d.from)&&(!d.to||i.date<=d.to)).length;document.getElementById('pdRepSummary').innerHTML=`<div class="grid kpis"><div class="card kpi"><div class="label">Alumnos</div><div class="value">${d.students.length}</div><div class="hint">${esc3(groupName(d.gid))}</div></div><div class="card kpi"><div class="label">Promedio</div><div class="value">${av===null?'—':av.toFixed(1)}</div><div class="hint">Calificaciones capturadas</div></div><div class="card kpi"><div class="label">Asistencia</div><div class="value">${pct(at)}</div><div class="hint">P + R / registros</div></div><div class="card kpi"><div class="label">Incidencias</div><div class="value">${inc}</div><div class="hint">En el periodo</div></div></div><div class="card"><div class="section-title"><h2>Reporte del grupo</h2><span class="note">${d.from||'Inicio'} → ${d.to||'Sin límite'}</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Alumno</th><th>Promedio</th><th>Asistencia</th><th>Incidencias</th></tr></thead><tbody>${d.students.map(s=>{const si=(db.incidents||[]).filter(i=>i.studentId===s.id&&(!d.from||i.date>=d.from)&&(!d.to||i.date<=d.to)).length;return `<tr><td><b>${esc3(s.name)}</b></td><td>${studentAvg3(s)===null?'—':studentAvg3(s).toFixed(1)}</td><td>${pct(studentAtt3(s,d.from,d.to))}</td><td>${si}</td></tr>`}).join('')||'<tr><td colspan="4" class="empty">No hay alumnos en este grupo.</td></tr>'}</tbody></table></div></div>`}
  function groupPdf(){const d=getData();if(!window.jspdf?.jsPDF)return alert('No está disponible el generador PDF.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'});doc.setFontSize(18);doc.text('Panorama Docente',14,16);doc.setFontSize(12);doc.text(`Reporte de grupo · ${groupName(d.gid)}`,14,24);doc.setFontSize(9);doc.text(`Periodo: ${d.from||'Inicio'} a ${d.to||'Actualidad'} · Ciclo ${db.cycle}`,14,31);let y=42;doc.setFontSize(9);doc.text('Alumno',14,y);doc.text('Promedio',130,y);doc.text('Asistencia',165,y);doc.text('Incidencias',210,y);y+=6;d.students.forEach(s=>{if(y>190){doc.addPage();y=18}const a=studentAvg3(s),at=studentAtt3(s,d.from,d.to),inc=(db.incidents||[]).filter(i=>i.studentId===s.id&&(!d.from||i.date>=d.from)&&(!d.to||i.date<=d.to)).length;doc.text(String(s.name).slice(0,55),14,y);doc.text(a===null?'—':a.toFixed(1),130,y);doc.text(at===null?'—':at.toFixed(1)+'%',165,y);doc.text(String(inc),210,y);y+=6});doc.setFontSize(8);doc.text('Documento generado desde Panorama Docente',14,202);doc.save(`Reporte_${d.gid}_${today()}.pdf`)}
  function groupExcel(){const d=getData();const rows=d.students.map(s=>({Alumno:s.name,Grupo:groupName(d.gid),Promedio:studentAvg3(s)===null?'':Number(studentAvg3(s).toFixed(2)),Asistencia:studentAtt3(s,d.from,d.to)===null?'':Number(studentAtt3(s,d.from,d.to).toFixed(2)),Incidencias:(db.incidents||[]).filter(i=>i.studentId===s.id&&(!d.from||i.date>=d.from)&&(!d.to||i.date<=d.to)).length}));if(!window.XLSX)return alert('No está disponible el exportador Excel.');const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Reporte');XLSX.writeFile(wb,`Reporte_${d.gid}_${today()}.xlsx`)}
  const originalSetView=window.setView;
  window.setView=function(v){if(v==='reportes'){view=v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.getElementById('pageTitle').textContent='Reportes';document.getElementById('pageSubtitle').textContent='Cortes para familias, asesores y dirección';return renderReportes()}return originalSetView(v)};
  window.PD_REPORTES={render:renderReportes};
})();
