/* Panorama Docente — módulo de Trabajos */
(function(){
function e(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function opts(groupId,cur){return (PD_CONFIG.subjects||[]).filter(s=>PD_CONFIG.subjectAllowedForGroup(s.id,groupId)).map(s=>`<option value="${s.id}" ${s.id===cur?'selected':''}>${e(s.name)}</option>`).join('')}
function trabajos(){let rows=[...(db.activities||[])].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(a=>{let total=studentsOf(a.groupId).length,done=db.grades.filter(g=>g.activityId===a.id).length,linked=(db.prints||[]).some(p=>p.activityId===a.id);return `<tr><td>${e(a.date)}</td><td><b>${e(a.title)}</b>${linked?'<br><small>Generado desde Impresiones</small>':''}</td><td>${e(groupName(a.groupId))}</td><td>${e(subjectName(a.subjectId))}</td><td>${a.points||10}</td><td>${done}/${total}</td><td><button class="btn" onclick="openActivityModal('${a.id}')">Editar</button> <button class="btn" onclick="deleteActivity('${a.id}')">Eliminar</button></td></tr>`}).join('');return `<div class="toolbar"><button class="btn primary" onclick="openActivityModal()">＋ Nueva actividad</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Actividad</th><th>Grupo</th><th>Materia</th><th>Valor</th><th>Entregas</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">No hay actividades.</td></tr>'}</tbody></table></div></div>`}
function openActivityModal(id){let a=id&&db.activities.find(x=>x.id===id),group=a?.groupId||db.groups.find(g=>g.active)?.id||db.groups[0]?.id||'',sid=a?.subjectId||'vida23',m=document.createElement('div');m.id='pdActivityModal';m.className='modal-backdrop';m.innerHTML=`<div class="modal-card pd-activity-card"><div class="modal-head"><h3>${a?'Editar actividad':'Nueva actividad'}</h3><button type="button" aria-label="Cerrar" onclick="this.closest('.modal-backdrop').remove()">×</button></div><div class="form-grid"><label>Grupo<select id="pdActGroup">${db.groups.map(g=>`<option value="${g.id}" ${g.id===group?'selected':''}>${e(g.name)}</option>`).join('')}</select></label><label>Materia<select id="pdActSubject">${opts(group,sid)}</select></label><label>Fecha<input id="pdActDate" type="date" value="${a?.date||today()}"></label><label>Valor<input id="pdActPoints" type="number" min="1" max="100" step="0.1" value="${a?.points||10}"></label><label style="grid-column:1/-1">Actividad<input id="pdActTitle" maxlength="120" value="${e(a?.title||'')}" placeholder="Nombre de la actividad"></label></div><div class="pd-modal-actions"><button type="button" class="btn" onclick="this.closest('.modal-backdrop').remove()">Cancelar</button><button type="button" class="btn primary" onclick="saveActivityModal('${id||''}')">Guardar</button></div></div>`;document.body.appendChild(m);document.getElementById('pdActGroup').onchange=function(){let g=this.value,s=document.getElementById('pdActSubject');s.innerHTML=opts(g,s.value);if(!s.value)s.selectedIndex=0};document.getElementById('pdActTitle').focus()}
function saveActivityModal(id){let groupId=pdActGroup.value,title=pdActTitle.value.trim(),date=pdActDate.value,points=Number(pdActPoints.value),subjectId=PD_WORKS.inferSubject(groupId,pdActSubject.value);if(!title||!date||!groupId||!subjectId||!(points>0)){alert('Completa los datos de la actividad.');return}if(id){let a=db.activities.find(x=>x.id===id);a.groupId=groupId;a.title=title;a.date=date;a.points=points;a.subjectId=subjectId}else PD_WORKS.getOrCreate({groupId,title,date,subjectId,points,source:'trabajo'});save();document.getElementById('pdActivityModal')?.remove();render()}
function deleteActivity(id){let a=db.activities.find(x=>x.id===id);if(!a)return;if((db.prints||[]).some(p=>p.activityId===id)){alert('Esta actividad está vinculada a una impresión y sus pagos/adeudos. No se elimina para proteger el historial. Puedes editarla.');return}if(!confirm(`¿Eliminar «${a.title}»? También se eliminarán sus calificaciones.`))return;db.grades=db.grades.filter(g=>g.activityId!==id);db.activities=db.activities.filter(x=>x.id!==id);save();render()}
window.trabajos=trabajos;window.openActivityModal=openActivityModal;window.saveActivityModal=saveActivityModal;window.deleteActivity=deleteActivity;
})();
