const KEY='panoramaDocente_v1';
const base={cycle:'2026-2027',subjects:[{id:'bio1',name:'Biología',grades:['1']} ,{id:'vida23',name:'Vida Saludable',grades:['2','3']}],groups:[],students:[],attendance:[],activities:[],grades:[],log:[],incidents:[]};
for(let g=1;g<=3;g++) for(const l of ['A','B','C','D','E']) base.groups.push({id:`${g}${l}`,name:`${g}º ${l}`,grade:String(g),active:true});
let db=load(); let view='dashboard';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(base)}catch{return structuredClone(base)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function uid(p='id'){return p+'_'+Math.random().toString(36).slice(2,9)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function groupName(id){return db.groups.find(g=>g.id===id)?.name||id||'—'}
function subjectName(id){return db.subjects.find(s=>s.id===id)?.name||id||'—'}
function studentsOf(group){return db.students.filter(s=>s.groupId===group)}
function avg(nums){nums=nums.filter(n=>Number.isFinite(n));return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:0}
function fmt(n){return Number(n||0).toFixed(1)}
function setView(v){view=v;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const titles={dashboard:['Dashboard','Resumen de tu gestión docente'],alumnos:['Alumnos','Padrón, grupos y movimientos'],asistencia:['Asistencia','Registro rápido por grupo y fecha'],trabajos:['Trabajos','Actividades y entregas'],calificaciones:['Calificaciones','Evaluación y promedios'],bitacora:['Temas / Bitácora','Registro diario y avance del programa'],incidencias:['Incidencias','Seguimiento disciplinario y académico'],reportes:['Reportes','Cortes para familias, asesores y dirección'],config:['Configuración','Importación, respaldo y parámetros']};document.getElementById('pageTitle').textContent=titles[v][0];document.getElementById('pageSubtitle').textContent=titles[v][1];render()}
function render(){const c=document.getElementById('content'); c.innerHTML=({dashboard:dashboard,alumnos:alumnos,asistencia:asistencia,trabajos:trabajos,calificaciones:calificaciones,bitacora:bitacora,incidencias:incidencias,reportes:reportes,config:config}[view])()}
function dashboard(){const n=db.students.length, groups=db.groups.filter(g=>g.active).length;const att=db.attendance;const present=att.filter(a=>a.status==='P').length;const attendance=att.length?present/att.length*100:0;const grades=db.grades.map(g=>+g.value);const overall=avg(grades);const pending=db.activities.reduce((a,x)=>a+studentsOf(x.groupId).filter(s=>!db.grades.some(g=>g.activityId===x.id&&g.studentId===s.id)).length,0);const risk=db.students.filter(s=>studentAvg(s.id)<6.9||studentAttendance(s.id)<80).length;const advance=topicAdvance();return `<div class="grid kpis"><div class="card kpi"><div class="label">Alumnos registrados</div><div class="value">${n}</div><div class="hint">Padrón actual</div></div><div class="card kpi"><div class="label">Grupos activos</div><div class="value">${groups}</div><div class="hint">1.º a 3.º</div></div><div class="card kpi"><div class="label">Asistencia</div><div class="value">${att.length?fmt(attendance):'—'}%</div><div class="hint">Sobre registros capturados</div></div><div class="card kpi"><div class="label">Promedio</div><div class="value">${grades.length?fmt(overall):'—'}</div><div class="hint">Calificaciones capturadas</div></div></div><div class="grid two"><div class="card"><div class="section-title"><h2>Grupos</h2><button class="btn" onclick="setView('alumnos')">Ver alumnos</button></div><div class="bars">${db.groups.filter(g=>g.active).map(g=>{const sa=studentAvgGroup(g.id);return `<div class="barrow"><span>${esc(g.name)}</span><div class="progress"><span style="width:${Math.min(100,sa*10)}%"></span></div><b>${sa?fmt(sa):'—'}</b></div>`}).join('')}</div></div><div class="card"><div class="section-title"><h2>Atención prioritaria</h2></div><div class="note"><b>${risk}</b> alumno(s) en posible riesgo académico/asistencia.</div><div style="height:10px"></div><div class="note"><b>${pending}</b> entregas pendientes según actividades registradas.</div><div style="height:10px"></div><div class="note">Avance de bitácora: <b>${advance}%</b></div></div></div><div class="card" style="margin-top:16px"><div class="section-title"><h2>Actividad reciente</h2></div>${recent()}</div>`}
function recent(){const items=[...db.log.map(x=>({date:x.date,text:`${groupName(x.groupId)} · ${subjectName(x.subjectId)} · ${x.topic}`})),...db.incidents.map(x=>({date:x.date,text:`Incidencia · ${studentName(x.studentId)} · ${x.type}`}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);return items.length?`<div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Registro</th></tr>${items.map(x=>`<tr><td>${x.date}</td><td>${esc(x.text)}</td></tr>`).join('')}</table></div>`:`<div class="empty">Aún no hay registros.</div>`}
function studentName(id){const s=db.students.find(x=>x.id===id);return s?s.name:'Alumno eliminado'}
function studentAvg(id){return avg(db.grades.filter(g=>g.studentId===id).map(g=>+g.value))}
function studentAvgGroup(g){return avg(db.grades.filter(x=>db.students.find(s=>s.id===x.studentId)?.groupId===g).map(x=>+x.value))}
function studentAttendance(id){const a=db.attendance.filter(x=>x.studentId===id);return a.length?a.filter(x=>x.status==='P').length/a.length*100:100}
function topicAdvance(){return db.log.length?Math.min(100,Math.round(db.log.length/Math.max(1,db.students.length/20)*10)):0}
function alumnos(){return `<div class="toolbar"><input id="studentSearch" placeholder="Buscar alumno…" oninput="filterStudents()"><select id="groupFilter" onchange="filterStudents()"><option value="">Todos los grupos</option>${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><button class="btn primary" onclick="openStudentModal()">＋ Alumno</button><button class="btn" onclick="setView('config')">Importar Excel</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Alumno</th><th>Grupo</th><th>Promedio</th><th>Asistencia</th><th>Estado</th><th></th></tr></thead><tbody id="studentRows">${studentRows()}</tbody></table></div></div>`}
function studentRows(){return db.students.map(s=>`<tr data-name="${esc(s.name.toLowerCase())}" data-group="${s.groupId}"><td><b>${esc(s.name)}</b><br><small>${esc(s.curp||'Sin CURP')}</small></td><td>${groupName(s.groupId)}</td><td>${studentAvg(s.id)?fmt(studentAvg(s.id)):'—'}</td><td>${db.attendance.filter(a=>a.studentId===s.id).length?fmt(studentAttendance(s.id))+'%':'—'}</td><td>${studentAvg(s.id)&&studentAvg(s.id)<6.9?'<span class="badge bad">Atención</span>':'<span class="badge good">Normal</span>'}</td><td><button class="btn" onclick="openStudentModal('${s.id}')">Editar</button></td></tr>`).join('')||`<tr><td colspan="6" class="empty">No hay alumnos. Importa un Excel desde Configuración.</td></tr>`}
function filterStudents(){const q=document.getElementById('studentSearch').value.toLowerCase(),g=document.getElementById('groupFilter').value;document.querySelectorAll('#studentRows tr').forEach(r=>{r.style.display=(!q||r.dataset.name.includes(q))&&(!g||r.dataset.group===g)?'':'none'})}
function asistencia(){const group=db.groups.find(g=>g.active);return `<div class="toolbar"><select id="attGroup">${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><select id="attSubject">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><input type="date" id="attDate" value="${today()}"><button class="btn primary" onclick="loadAttendance()">Abrir lista</button></div><div id="attList" class="card"><div class="empty">Selecciona grupo y fecha.</div></div>`}
function loadAttendance(){const g=document.getElementById('attGroup').value,d=document.getElementById('attDate').value,s=document.getElementById('attSubject').value;const list=studentsOf(g);document.getElementById('attList').innerHTML=`<div class="section-title"><h2>${groupName(g)} · ${subjectName(s)} · ${d}</h2><button class="btn primary" onclick="saveAttendance('${g}','${s}','${d}')">Guardar asistencia</button></div><div class="table-wrap"><table class="table"><tr><th>#</th><th>Alumno</th><th>Estado</th></tr>${list.map((x,i)=>{const old=db.attendance.find(a=>a.studentId===x.id&&a.date===d&&a.subjectId===s);return `<tr><td>${i+1}</td><td>${esc(x.name)}</td><td><select class="attStatus" data-student="${x.id}"><option value="P" ${old?.status==='P'?'selected':''}>Presente</option><option value="F" ${old?.status==='F'?'selected':''}>Falta</option><option value="J" ${old?.status==='J'?'selected':''}>Justificada</option><option value="R" ${old?.status==='R'?'selected':''}>Retardo</option></select></td></tr>`}).join('')}</table></div>`}
function saveAttendance(g,s,d){document.querySelectorAll('.attStatus').forEach(el=>{const i=db.attendance.findIndex(a=>a.studentId===el.dataset.student&&a.date===d&&a.subjectId===s);const obj={id:i>=0?db.attendance[i].id:uid('att'),studentId:el.dataset.student,groupId:g,subjectId:s,date:d,status:el.value};if(i>=0)db.attendance[i]=obj;else db.attendance.push(obj)});save();alert('Asistencia guardada.');render()}
function trabajos(){return `<div class="toolbar"><button class="btn primary" onclick="openActivityModal()">＋ Nueva actividad</button></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Actividad</th><th>Grupo</th><th>Materia</th><th>Valor</th><th>Entregas</th></tr>${db.activities.map(a=>{const total=studentsOf(a.groupId).length,done=db.grades.filter(g=>g.activityId===a.id).length;return `<tr><td>${a.date}</td><td><b>${esc(a.title)}</b><br><small>${esc(a.topic||'')}</small></td><td>${groupName(a.groupId)}</td><td>${subjectName(a.subjectId)}</td><td>${a.points}</td><td>${done}/${total}</td></tr>`}).join('')||`<tr><td colspan="6" class="empty">No hay actividades.</td></tr>`}</table></div></div>`}
function calificaciones(){return `<div class="toolbar"><select id="gradeGroup" onchange="renderGradeTable()"><option value="">Selecciona grupo</option>${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><select id="gradeSubject" onchange="renderGradeTable()"><option value="">Todas las materias</option>${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div id="gradeTable" class="card"><div class="empty">Selecciona un grupo.</div></div>`}
function renderGradeTable(){const g=document.getElementById('gradeGroup').value;if(!g)return;const sid=document.getElementById('gradeSubject').value;const acts=db.activities.filter(a=>a.groupId===g&&(!sid||a.subjectId===sid));document.getElementById('gradeTable').innerHTML=`<div class="section-title"><h2>${groupName(g)}</h2><button class="btn primary" onclick="saveGradeInputs()">Guardar</button></div><div class="table-wrap"><table class="table"><tr><th>Alumno</th>${acts.map(a=>`<th title="${esc(a.title)}">${esc(a.title.slice(0,14))}</th>`).join('')}<th>Promedio</th></tr>${studentsOf(g).map(s=>`<tr><td>${esc(s.name)}</td>${acts.map(a=>{const old=db.grades.find(x=>x.activityId===a.id&&x.studentId===s.id);return `<td><input class="gradeInput" data-student="${s.id}" data-activity="${a.id}" type="number" min="0" max="${a.points}" step="0.1" value="${old?.value??''}" style="width:75px"></td>`}).join('')}<td><b>${studentAvg(s.id)?fmt(studentAvg(s.id)):'—'}</b></td></tr>`).join('')}</table></div>`}
function saveGradeInputs(){document.querySelectorAll('.gradeInput').forEach(el=>{if(el.value==='')return;const i=db.grades.findIndex(g=>g.studentId===el.dataset.student&&g.activityId===el.dataset.activity);const obj={id:i>=0?db.grades[i].id:uid('gr'),studentId:el.dataset.student,activityId:el.dataset.activity,value:+el.value};if(i>=0)db.grades[i]=obj;else db.grades.push(obj)});save();alert('Calificaciones guardadas.');renderGradeTable()}
function bitacora(){return `<div class="toolbar"><button class="btn primary" onclick="openLogModal()">＋ Registrar tema</button></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Grupo</th><th>Materia</th><th>Tema</th><th>Estado</th><th>Observación</th></tr>${[...db.log].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${x.date}</td><td>${groupName(x.groupId)}</td><td>${subjectName(x.subjectId)}</td><td><b>${esc(x.topic)}</b></td><td>${esc(x.status)}</td><td>${esc(x.notes||'')}</td></tr>`).join('')||`<tr><td colspan="6" class="empty">No hay temas registrados.</td></tr>`}</table></div></div>`}
function incidencias(){return `<div class="toolbar"><button class="btn primary" onclick="openIncidentModal()">＋ Nueva incidencia</button></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Alumno</th><th>Grupo</th><th>Tipo</th><th>Gravedad</th><th>Seguimiento</th></tr>${[...db.incidents].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${x.date}</td><td>${esc(studentName(x.studentId))}</td><td>${groupName(db.students.find(s=>s.id===x.studentId)?.groupId)}</td><td>${esc(x.type)}</td><td><span class="badge ${x.severity==='Alta'?'bad':x.severity==='Media'?'warn':'good'}">${esc(x.severity)}</span></td><td>${esc(x.followup||'Pendiente')}</td></tr>`).join('')||`<tr><td colspan="6" class="empty">No hay incidencias.</td></tr>`}</table></div></div>`}
function reportes(){return `<div class="grid three"><div class="card"><h2>📊 Reporte de calificaciones</h2><p class="note">Exporta alumnos, actividades y promedios a Excel.</p><button class="btn primary" onclick="exportGrades()">Exportar Excel</button></div><div class="card"><h2>📋 Reporte de asistencia</h2><p class="note">Exporta registros capturados.</p><button class="btn primary" onclick="exportAttendance()">Exportar Excel</button></div><div class="card"><h2>⚠️ Incidencias</h2><p class="note">Genera un PDF resumido del seguimiento.</p><button class="btn primary" onclick="exportIncidentPDF()">Exportar PDF</button></div></div><div class="card" style="margin-top:16px"><div class="section-title"><h2>Corte de grupo</h2></div><div class="toolbar"><select id="cutGroup">${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><button class="btn primary" onclick="exportGroupPDF()">Generar PDF</button><button class="btn" onclick="exportGroupExcel()">Generar Excel</button></div><div class="note">El corte incluye alumnos, promedio, asistencia e incidencias del grupo.</div></div>`}
function config(){return `<div class="grid two"><div class="card"><div class="section-title"><h2>Importar alumnos desde Excel</h2></div><p class="note">Columnas recomendadas: <b>Nombre, CURP, Grupo</b>. También reconoce Nombre + Apellido paterno + Apellido materno.</p><input type="file" id="xlsxFile" accept=".xlsx,.xls,.csv"><div style="height:10px"></div><button class="btn primary" onclick="importExcel()">Importar padrón</button></div><div class="card"><h2>Respaldo</h2><p class="note">Guarda todos los datos de esta app en un archivo JSON para poder recuperarlos.</p><button class="btn" onclick="backup()">Exportar respaldo</button><div style="height:8px"></div><input type="file" id="backupFile" accept=".json"><button class="btn" onclick="restore()">Restaurar respaldo</button></div></div><div class="card" style="margin-top:16px"><h2>Parámetros</h2><div class="form-grid"><label>Ciclo escolar<input value="2026–2027" disabled></label><label>Materias<input value="Biología · Vida Saludable" disabled></label></div><div style="height:12px"></div><div class="note">Los datos actuales se guardan localmente en este navegador. Esta primera versión está preparada como MVP para GitHub Pages; la siguiente fase puede conectar una base de datos para sincronización multi-dispositivo.</div></div>`}
function openModal(title,html){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
document.getElementById('modalClose').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function openStudentModal(id){const s=db.students.find(x=>x.id===id)||{};openModal(id?'Editar alumno':'Nuevo alumno',`<div class="form"><div class="form-grid"><label>Nombre completo<input id="fName" value="${esc(s.name||'')}"></label><label>CURP<input id="fCurp" value="${esc(s.curp||'')}"></label></div><label>Grupo<select id="fGroup">${db.groups.map(g=>`<option value="${g.id}" ${s.groupId===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><button class="btn primary" onclick="saveStudent('${id||''}')">Guardar</button></div>`)}
function saveStudent(id){const name=document.getElementById('fName').value.trim(),curp=document.getElementById('fCurp').value.trim(),groupId=document.getElementById('fGroup').value;if(!name)return alert('Escribe el nombre.');if(id){Object.assign(db.students.find(s=>s.id===id),{name,curp,groupId})}else db.students.push({id:uid('stu'),name,curp,groupId});save();closeModal();render()}
function openActivityModal(){openModal('Nueva actividad',`<div class="form"><div class="form-grid"><label>Fecha<input id="aDate" type="date" value="${today()}"></label><label>Valor máximo<input id="aPoints" type="number" value="10" min="1"></label></div><div class="form-grid"><label>Grupo<select id="aGroup">${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></label><label>Materia<select id="aSubject">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label></div><label>Actividad<input id="aTitle" placeholder="Ej. Mapa conceptual"></label><label>Tema<input id="aTopic" placeholder="Tema asociado"></label><button class="btn primary" onclick="saveActivity()">Crear actividad</button></div>`)}
function saveActivity(){db.activities.push({id:uid('act'),date:document.getElementById('aDate').value,points:+document.getElementById('aPoints').value,groupId:document.getElementById('aGroup').value,subjectId:document.getElementById('aSubject').value,title:document.getElementById('aTitle').value.trim(),topic:document.getElementById('aTopic').value.trim()});save();closeModal();render()}
function openLogModal(){openModal('Registrar tema visto',`<div class="form"><div class="form-grid"><label>Fecha<input id="lDate" type="date" value="${today()}"></label><label>Estado<select id="lStatus"><option>Clase normal</option><option>Suspensión</option><option>Actividad sindical</option><option>Consejo técnico</option><option>Vacaciones</option><option>Puente</option><option>Cambio de actividad</option><option>Otra situación</option></select></label></div><div class="form-grid"><label>Grupo<select id="lGroup">${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></label><label>Materia<select id="lSubject">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label></div><label>Tema<input id="lTopic" placeholder="Tema visto o motivo de suspensión"></label><label>Observación<textarea id="lNotes"></textarea></label><button class="btn primary" onclick="saveLog()">Guardar bitácora</button></div>`)}
function saveLog(){db.log.push({id:uid('log'),date:document.getElementById('lDate').value,groupId:document.getElementById('lGroup').value,subjectId:document.getElementById('lSubject').value,topic:document.getElementById('lTopic').value.trim(),status:document.getElementById('lStatus').value,notes:document.getElementById('lNotes').value.trim()});save();closeModal();render()}
function openIncidentModal(){openModal('Nueva incidencia',`<div class="form"><div class="form-grid"><label>Fecha<input id="iDate" type="date" value="${today()}"></label><label>Alumno<select id="iStudent">${db.students.map(s=>`<option value="${s.id}">${esc(s.name)} · ${groupName(s.groupId)}</option>`).join('')}</select></label></div><div class="form-grid"><label>Tipo<select id="iType"><option>Conducta</option><option>Académica</option><option>Asistencia</option><option>Disciplina</option><option>Convivencia</option><option>Trabajo</option><option>Otro</option></select></label><label>Gravedad<select id="iSeverity"><option>Baja</option><option>Media</option><option>Alta</option></select></label></div><label>Descripción<textarea id="iDesc"></textarea></label><label>Seguimiento<input id="iFollow" placeholder="Ej. Llamado de atención / comunicación con familia"></label><button class="btn primary" onclick="saveIncident()">Guardar incidencia</button></div>`)}
function saveIncident(){db.incidents.push({id:uid('inc'),date:document.getElementById('iDate').value,studentId:document.getElementById('iStudent').value,type:document.getElementById('iType').value,severity:document.getElementById('iSeverity').value,description:document.getElementById('iDesc').value,followup:document.getElementById('iFollow').value});save();closeModal();render()}
function openQuick(){openModal('Registro rápido',`<div class="grid three"><button class="btn" onclick="closeModal();setView('asistencia')">📋 Asistencia</button><button class="btn" onclick="closeModal();setView('trabajos')">📝 Trabajo</button><button class="btn" onclick="closeModal();setView('bitacora')">📚 Tema visto</button><button class="btn" onclick="closeModal();setView('incidencias')">⚠️ Incidencia</button></div>`)}
document.getElementById('quickAdd').onclick=openQuick;
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function xlsx(rows,name){const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Reporte');XLSX.writeFile(wb,name+'.xlsx')}
function exportGrades(){xlsx(db.students.map(s=>({Alumno:s.name,CURP:s.curp||'',Grupo:groupName(s.groupId),Promedio:studentAvg(s.id)?fmt(studentAvg(s.id)):''})),`calificaciones_2026-2027`)}
function exportAttendance(){xlsx(db.attendance.map(a=>({Fecha:a.date,Alumno:studentName(a.studentId),Grupo:groupName(a.groupId),Materia:subjectName(a.subjectId),Estado:a.status})),`asistencia_2026-2027`)}
function pdf(title,lines,name){const {jsPDF}=window.jspdf;const d=new jsPDF();d.setFontSize(18);d.text(title,14,18);d.setFontSize(10);let y=30;lines.forEach(l=>{const arr=d.splitTextToSize(l,180);if(y+arr.length*6>280){d.addPage();y=18}d.text(arr,14,y);y+=arr.length*6+3});d.save(name+'.pdf')}
function exportIncidentPDF(){pdf('Reporte de incidencias 2026–2027',db.incidents.map(x=>`${x.date} | ${studentName(x.studentId)} | ${x.type} | ${x.severity} | ${x.description||''} | Seguimiento: ${x.followup||'Pendiente'}`),'reporte_incidencias')}
function exportGroupPDF(){const g=document.getElementById('cutGroup').value;const ss=studentsOf(g);const lines=[`Grupo: ${groupName(g)}`,`Alumnos: ${ss.length}`,`Promedio del grupo: ${fmt(studentAvgGroup(g))}`,`Incidencias: ${db.incidents.filter(i=>db.students.find(s=>s.id===i.studentId)?.groupId===g).length}`,``,`ALUMNOS`];ss.forEach(s=>lines.push(`${s.name} | Promedio: ${studentAvg(s.id)?fmt(studentAvg(s.id)):'—'} | Asistencia: ${db.attendance.filter(a=>a.studentId===s.id).length?fmt(studentAttendance(s.id))+'%':'—'}`));pdf('Corte académico — 2026–2027',lines,`corte_${g}`)}
function exportGroupExcel(){const g=document.getElementById('cutGroup').value;xlsx(studentsOf(g).map(s=>({Alumno:s.name,CURP:s.curp||'',Grupo:groupName(g),Promedio:studentAvg(s.id)?fmt(studentAvg(s.id)):'',Asistencia:db.attendance.filter(a=>a.studentId===s.id).length?fmt(studentAttendance(s.id))+'%':'',Incidencias:db.incidents.filter(i=>i.studentId===s.id).length})),`corte_${g}`)}
function importExcel(){const f=document.getElementById('xlsxFile').files[0];if(!f)return alert('Selecciona un archivo.');const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let added=0;rows.forEach(row=>{const keys=Object.keys(row).map(k=>[k,k.toLowerCase().trim()]);const get=(...names)=>{const k=keys.find(([a,b])=>names.includes(b));return k?row[k[0]]:''};let name=get('nombre completo','nombre');if(!name)name=[get('apellido paterno','paterno'),get('apellido materno','materno'),get('nombres')].filter(Boolean).join(' ');let raw=String(get('grupo')||'').toUpperCase().replace('º','').replace(' ','');let grade=raw.match(/[123]/)?.[0]||'1',letter=raw.match(/[ABCDE]/)?.[0]||'A';let groupId=grade+letter;if(!db.groups.some(g=>g.id===groupId))groupId='1A';if(name){db.students.push({id:uid('stu'),name:String(name).trim(),curp:String(get('curp')||'').trim(),groupId});added++}});save();alert(`Importación terminada: ${added} alumno(s).`);setView('alumnos')}catch(err){alert('No se pudo leer el archivo: '+err.message)}};r.readAsArrayBuffer(f)}
function backup(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='panorama_docente_respaldo_2026-2027.json';a.click()}
function restore(){const f=document.getElementById('backupFile').files[0];if(!f)return alert('Selecciona un respaldo JSON.');const r=new FileReader();r.onload=e=>{try{db=JSON.parse(e.target.result);save();alert('Respaldo restaurado.');render()}catch{alert('Respaldo inválido.')}};r.readAsText(f)}
document.getElementById('demoBtn').onclick=()=>{if(db.students.length&&!confirm('Se agregarán datos demo a los existentes. ¿Continuar?'))return;const names=['Ana López','Bruno García','Carla Pérez','Diego Díaz','Elena Cruz','Fabián Ruiz','Gabriela Soto','Hugo León','Irene Mora','José Silva'];names.forEach((name,i)=>db.students.push({id:uid('stu'),name,curp:'',groupId:['1A','1B','1C','2A','2B'][i%5]}));db.log.push({id:uid('log'),date:today(),groupId:'1A',subjectId:'bio1',topic:'Introducción a la Biología',status:'Clase normal',notes:''});save();render()};
document.getElementById('resetBtn').onclick=()=>{if(confirm('Esto eliminará todos los datos guardados en este navegador. ¿Continuar?')){db=structuredClone(base);save();render()}};
render();
