/* Panorama Docente — integración de impresiones con trabajos y calificaciones */
(function(){
  if(!window.db || !Array.isArray(db.activities)) return;
  db.printJobs = Array.isArray(db.printJobs) ? db.printJobs : [];
  db.printPayments = Array.isArray(db.printPayments) ? db.printPayments : [];
  function persist(){ if(typeof save==='function') save(); }
  function renderPrints(){
    const panel=document.getElementById('pdPrintPanel'); if(!panel)return;
    const jobs=db.printJobs||[];
    const total=jobs.reduce((n,j)=>n+j.cost*j.studentIds.length,0);
    const paid=jobs.reduce((n,j)=>n+j.cost*j.studentIds.filter(id=>db.printPayments.some(p=>p.jobId===j.id&&p.studentId===id&&p.paid)).length,0);
    const debt=total-paid;
    const people=new Set(jobs.flatMap(j=>j.studentIds.filter(id=>!db.printPayments.some(p=>p.jobId===j.id&&p.studentId===id&&p.paid))));
    const k=document.getElementById('pdPrintKpis'); if(k) k.innerHTML=`<div class="card"><b>Generado</b><div style="font-size:24px">$${total.toFixed(2)}</div></div><div class="card"><b>Cobrado</b><div style="font-size:24px">$${paid.toFixed(2)}</div></div><div class="card"><b>Pendiente</b><div style="font-size:24px">$${debt.toFixed(2)}</div></div><div class="card"><b>Alumnos con adeudo</b><div style="font-size:24px">${people.size}</div></div>`;
    const list=document.getElementById('pdPrintList'); if(!list)return;
    list.innerHTML=`<div class="card"><div class="section-title"><h2>Trabajos impresos</h2></div><div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Actividad</th><th>Grupo</th><th>Costo</th><th>Pagos</th><th>Pendiente</th><th></th></tr>${jobs.slice().reverse().map(j=>{const n=j.studentIds.length,pg=j.studentIds.filter(id=>db.printPayments.some(p=>p.jobId===j.id&&p.studentId===id&&p.paid)).length;return `<tr><td>${j.date}</td><td><b>${esc(j.title)}</b></td><td>${groupName(j.groupId)}</td><td>$${j.cost.toFixed(2)}</td><td>${pg}/${n}</td><td>$${((n-pg)*j.cost).toFixed(2)}</td><td><button class="btn" onclick="window.pdOpenJob('${j.id}')">Pagos / calificación</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Aún no hay impresiones.</td></tr>'}</table></div></div>`;
    const sums={};jobs.forEach(j=>j.studentIds.forEach(id=>{if(!db.printPayments.some(p=>p.jobId===j.id&&p.studentId===id&&p.paid))sums[id]=(sums[id]||0)+j.cost}));
    document.getElementById('pdDebts').innerHTML=`<div class="card"><h2>Adeudos por alumno</h2>${Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([id,v])=>`<div style="display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid var(--line)"><span>${esc(studentName(id))} · ${groupName(db.students.find(s=>s.id===id)?.groupId)}</span><b>$${v.toFixed(2)}</b></div>`).join('')||'<div class="empty">No hay adeudos.</div>'}</div>`;
  }
  window.pdOpenJob=function(id){const j=db.printJobs.find(x=>x.id===id);if(!j)return;document.getElementById('pdPrintList').innerHTML=`<div class="card"><div class="section-title"><h2>${esc(j.title)} · ${groupName(j.groupId)}</h2><button class="btn" onclick="window.pdRenderPrints()">← Regresar</button></div><p>Costo de impresión: <b>$${j.cost.toFixed(2)}</b> por alumno. La actividad ya está creada en <b>Trabajos</b> y puede calificarse en <b>Calificaciones</b>.</p><div class="table-wrap"><table class="table"><tr><th>Alumno</th><th>Calificación</th><th>Pago</th></tr>${j.studentIds.map(id=>{const g=db.grades.find(x=>x.activityId===j.activityId&&x.studentId===id);const p=db.printPayments.find(x=>x.jobId===j.id&&x.studentId===id);return `<tr><td>${esc(studentName(id))}</td><td><input type="number" min="0" max="10" step="0.1" value="${g?.value??''}" onchange="window.pdGrade('${j.activityId}','${id}',this.value)" style="width:80px"></td><td><label><input type="checkbox" ${p?.paid?'checked':''} onchange="window.pdPaid('${j.id}','${id}',this.checked)"> Pagado</label></td></tr>`}).join('')}</table></div></div>`;document.getElementById('pdDebts').innerHTML='';};
  window.pdGrade=function(activityId,studentId,value){const n=Number(value);if(value===''||!Number.isFinite(n))return;const i=db.grades.findIndex(g=>g.activityId===activityId&&g.studentId===studentId);const o={id:i>=0?db.grades[i].id:uid('gr'),studentId,activityId,value:n};if(i>=0)db.grades[i]=o;else db.grades.push(o);persist()};
  window.pdPaid=function(jobId,studentId,paid){let p=db.printPayments.find(x=>x.jobId===jobId&&x.studentId===studentId);if(!p){p={id:uid('pay'),jobId,studentId,paid:false};db.printPayments.push(p)}p.paid=!!paid;p.paidAt=paid?new Date().toISOString():null;persist();window.pdOpenJob(jobId)};
  window.pdRenderPrints=renderPrints;
  window.pdCreatePrint=function(){const date=document.getElementById('pdDate').value,g=document.getElementById('pdGroup').value,s=document.getElementById('pdSubject').value,title=document.getElementById('pdTitle').value.trim(),cost=Number(document.getElementById('pdCost').value);if(!title||!Number.isFinite(cost)||cost<0)return alert('Escribe actividad y costo válido.');const ids=studentsOf(g).map(x=>x.id);if(!ids.length)return alert('Ese grupo no tiene alumnos registrados.');const activity={id:uid('act'),date,title,topic:title,groupId:g,subjectId:s,points:10,source:'impresion'};db.activities.push(activity);const job={id:uid('print'),activityId:activity.id,date,groupId:g,subjectId:s,title,cost,studentIds:ids};db.printJobs.push(job);persist();renderPrints();alert('Listo: se creó la impresión y también la actividad en Trabajos. Ahora puedes calificarla en Calificaciones.');};
  function init(){const nav=document.getElementById('nav');if(!nav||document.getElementById('pdPrintBtn'))return;const b=document.createElement('button');b.className='nav';b.id='pdPrintBtn';b.dataset.view='impresiones';b.textContent='🖨️ Impresiones / Adeudos';b.onclick=show;nav.appendChild(b)}
  function show(){document.getElementById('pdPrintPanel')?.remove();const p=document.createElement('div');p.id='pdPrintPanel';p.style.cssText='position:fixed;inset:0;background:rgba(12,28,42,.58);z-index:9990;display:flex;align-items:center;justify-content:center;padding:12px';p.innerHTML=`<div style="width:min(1100px,100%);max-height:94vh;overflow:auto;background:#fff;border-radius:18px;padding:18px"><div class="section-title"><div><h2>🖨️ Impresiones y adeudos</h2><small style="color:#687784">Control de pago + actividad + calificación</small></div><button class="btn" onclick="this.closest('#pdPrintPanel').remove()">Cerrar</button></div><div id="pdPrintKpis" class="grid three"></div><div class="card"><h2>Nueva impresión</h2><div class="toolbar"><input id="pdDate" type="date" value="${today()}"><select id="pdGroup">${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><select id="pdSubject">${db.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><input id="pdTitle" placeholder="Trabajo / actividad"><input id="pdCost" type="number" min="0" step="0.50" value="2"><button class="btn primary" onclick="pdCreatePrint()">Crear</button></div><small style="color:#687784">Al crearla, la actividad aparece automáticamente en Trabajos y en Calificaciones.</small></div><div id="pdPrintList"></div><div id="pdDebts"></div></div>`;document.body.appendChild(p);renderPrints()}
  const mo=new MutationObserver(init);mo.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
