const CACHE='panorama-docente-v33';
const VERSION='2026.09.01.40';
const SHELL=['./','./index.html','./styles.css','./app-config.js','./app.js','./modules.js','./policy.js','./sync.js','./impresiones.js','./asistencia-mejorada.js','./modules/trabajos-core.js','./modules/trabajos.js','./modules/bitacora.js','./modules/alumnos.js','./modules/incidencias.js','./modules/reportes.js','./modules/calificaciones.js','./modules/identidad.js'];
const EXTERNAL=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js','https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2'];
const SHELL_SET=new Set(SHELL.map(x=>new URL(x,self.location).pathname));
async function cacheResponse(cache,url,response){if(response&&response.ok){try{await cache.put(new Request(new URL(url,self.location).href),response.clone())}catch(e){}}return response}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);for(const u of SHELL){try{const r=await fetch(new Request(new URL(u,self.location).href,{cache:'no-store'}));await cacheResponse(c,u,r)}catch(err){}}for(const u of EXTERNAL){try{await c.add(u)}catch(err){}}await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('panorama-docente-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function findCachedApp(request){const c=await caches.open(CACHE);const url=new URL(request.url);return await c.match(new Request(url.href),{ignoreSearch:true})||await c.match(new Request(url.origin+url.pathname),{ignoreSearch:true})||await c.match(new Request(new URL('./index.html',self.location).href),{ignoreSearch:true})}
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const url=new URL(r.url),isNavigation=r.mode==='navigate',isShell=url.origin===self.location.origin&&SHELL_SET.has(url.pathname);if(isNavigation||isShell){e.respondWith((async()=>{const cached=await findCachedApp(r);if(cached){fetch(r,{cache:'no-store'}).then(async fresh=>{if(fresh&&fresh.ok){const c=await caches.open(CACHE);await cacheResponse(c,r.url.split('?')[0],fresh)}}).catch(()=>{});return cached}try{const fresh=await fetch(r,{cache:'no-store'});if(fresh&&fresh.ok){const c=await caches.open(CACHE);await cacheResponse(c,r.url.split('?')[0],fresh)}return fresh}catch(err){return await findCachedApp(new Request(new URL('./index.html',self.location).href))||new Response('Sin conexión y sin copia local disponible.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}})}})());return}e.respondWith((async()=>{const c=await caches.open(CACHE),cached=await c.match(r,{ignoreSearch:true});if(cached)return cached;try{const fresh=await fetch(r);if(fresh&&(fresh.ok||fresh.type==='opaque')){try{await c.put(r,fresh.clone())}catch(e){}}return fresh}catch(err){return await c.match(new Request(new URL('./index.html',self.location).href),{ignoreSearch:true})||new Response('',{status:503})}})())});