/* Panorama Docente — sincronización offline-first estable */
(function(){
const URL='https://dtmhffgpwxzdncbuoohb.supabase.co';
const KEY=['sb_publishable_','S_wZkfLNvx0mnHBLGHcfgg_Q_SkycdW'].join('');
const APP='panoramaDocente_v1', QUEUE='panoramaDocente_sync_queue_v1';
const S=window.supabase;if(!S?.createClient)return;
const client=S.createClient(URL,KEY);let busy=false,timer=null,started=false;
function badge(t){let b=document.getElementById('pdSync');if(!b){b=document.createElement('div');b.id='pdSync';b.textContent=t;document.body.appendChild(b)}else b.textContent=t}
function auth(){if(document.getElementById('pdAuth'))return;const e=document.createElement('div');e.id='pdAuth';e.innerHTML='<div class="box"><h2>Panorama Docente</h2><p>Inicia sesión para guardar tus datos en la nube. La aplicación sigue funcionando sin internet.</p><input id="pdEmail" type="email" placeholder="Correo electrónico" autocomplete="email"><input id="pdPass" type="password" placeholder="Contraseña" autocomplete="current-password"><button id="pdLogin">Iniciar sesión</button><button id="pdSignup" class="alt">Crear cuenta</button><div id="pdErr"></div></div>';document.body.appendChild(e);pdLogin.onclick=async()=>{pdErr.textContent='';const r=await client.auth.signInWithPassword({email:pdEmail.value.trim(),password:pdPass.value});if(r.error)pdErr.textContent=r.error.message};pdSignup.onclick=async()=>{pdErr.textContent='';const r=await client.auth.signUp({email:pdEmail.value.trim(),password:pdPass.value});if(r.error)pdErr.textContent=r.error.message;else if(!r.data.session)pdErr.textContent='Cuenta creada. Revisa tu correo si es necesario.'}}
function hide(){document.getElementById('pdAuth')?.remove()}
function markPending(){localStorage.setItem(QUEUE,'1');badge('📴 Guardado sin conexión')}
async function upload(){if(busy||!navigator.onLine)return;const{data:{session}}=await client.auth.getSession();if(!session)return;const raw=localStorage.getItem(APP);if(!raw)return;let data;try{data=JSON.parse(raw)}catch{return}busy=true;badge('☁️ Sincronizando…');const{error}=await client.from('docente_app_state').upsert({user_id:session.user.id,data,updated_at:new Date().toISOString()},{onConflict:'user_id'});busy=false;if(error){markPending();console.error('Supabase sync',error)}else{localStorage.removeItem(QUEUE);badge('☁️ Sincronizado')}}
async function pull(){if(!navigator.onLine)return false;const{data:{session}}=await client.auth.getSession();if(!session)return false;const{data,error}=await client.from('docente_app_state').select('data,updated_at').eq('user_id',session.user.id).maybeSingle();if(error){badge('📴 Modo local');return false}if(!data?.data){await upload();return false}const raw=JSON.stringify(data.data),local=localStorage.getItem(APP);if(raw===local){badge('☁️ Sincronizado');return false}localStorage.setItem(APP,raw);badge('☁️ Datos actualizados');return true}
const orig=Storage.prototype.setItem;if(!orig.__pd){function set(k,v){orig.call(this,k,v);if(k===APP){if(navigator.onLine){clearTimeout(timer);timer=setTimeout(upload,800)}else markPending()}}set.__pd=true;Storage.prototype.setItem=set}
window.addEventListener('offline',()=>badge('📴 Sin conexión · cambios guardados localmente'));
window.addEventListener('online',async()=>{badge('🌐 Conexión recuperada');await upload();const changed=await pull();if(changed&&typeof render==='function')render()});
async function start(){if(started)return;started=true;hide();if(!navigator.onLine){badge('📴 Sin conexión · modo local');return}badge('☁️ Conectando…');const changed=await pull();if(changed&&typeof render==='function')render();setInterval(async()=>{if(document.hidden||!navigator.onLine)return;const changed=await pull();if(changed&&typeof render==='function')render()},20000);client.channel('pd_sync_'+Date.now()).on('postgres_changes',{event:'*',schema:'public',table:'docente_app_state'},async()=>{const changed=await pull();if(changed&&typeof render==='function')render()}).subscribe()}
client.auth.onAuthStateChange((e,s)=>{if(s)start();else{started=false;auth()}});client.auth.getSession().then(({data:{session}})=>session?start():auth());
})();
