/* Panorama Docente — acceso local + sincronización opcional */
(function(){
const URL='https://dtmhffgpwxzdncbuoohb.supabase.co';const KEY=['sb_publishable_','S_wZkfLNvx0mnHBLGHcfgg_Q_SkycdW'].join('');const APP='panoramaDocente_v1',DIRTY=APP+'_dirty';const S=window.supabase;if(!S?.createClient)return;const client=S.createClient(URL,KEY);let busy=false,timer=null;
function badge(t){let b=document.getElementById('pdSync');if(!b){b=document.createElement('div');b.id='pdSync';b.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9998;background:#fff;border:1px solid #dce3e8;border-radius:999px;padding:7px 11px;font:12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 4px 18px rgba(0,0,0,.1);color:#687784';document.body.appendChild(b)}b.textContent=t}
async function upload(){if(busy||!navigator.onLine)return;const raw=localStorage.getItem(APP);if(!raw)return;const{data:{session}}=await client.auth.getSession();if(!session){badge('📴 Local · sin cuenta');return}busy=true;badge('☁️ Sincronizando…');const{error}=await client.from('docente_app_state').upsert({user_id:session.user.id,data:JSON.parse(raw),updated_at:new Date().toISOString()},{onConflict:'user_id'});busy=false;if(error){badge('📴 Pendiente de sincronizar')}else{localStorage.removeItem(DIRTY);badge('☁️ Sincronizado')}}
async function pull(){if(!navigator.onLine)return false;const raw=localStorage.getItem(APP);if(localStorage.getItem(DIRTY)){await upload();return false}const{data:{session}}=await client.auth.getSession();if(!session)return false;const{data,error}=await client.from('docente_app_state').select('data').eq('user_id',session.user.id).maybeSingle();if(error||!data?.data)return false;const remote=JSON.stringify(data.data);if(remote===raw){badge('☁️ Sincronizado');return false}localStorage.setItem(APP,remote);badge('☁️ Datos actualizados');return true}
const originalSet=Storage.prototype.setItem;if(!originalSet.__pd){function set(k,v){originalSet.call(this,k,v);if(k===APP){originalSet.call(this,DIRTY,'1');if(navigator.onLine){clearTimeout(timer);timer=setTimeout(upload,800)}else badge('📴 Guardado localmente')}}set.__pd=true;Storage.prototype.setItem=set}
window.addEventListener('offline',()=>badge('📴 Sin conexión · guardado local'));window.addEventListener('online',async()=>{badge('🌐 Conexión recuperada');await upload();await pull();if(typeof render==='function')render()});
/* La aplicación NO exige autenticación para abrir ni trabajar offline. Si existe una sesión válida, sincroniza; si no, permanece local. */
(async()=>{if(!navigator.onLine){badge('📴 Modo local');return}try{const{data:{session}}=await client.auth.getSession();if(session){await pull();setInterval(async()=>{if(!document.hidden&&navigator.onLine&&!localStorage.getItem(DIRTY))await pull()},20000);client.channel('pd_sync_'+Date.now()).on('postgres_changes',{event:'*',schema:'public',table:'docente_app_state'},async()=>{if(!localStorage.getItem(DIRTY)){const changed=await pull();if(changed&&typeof render==='function')render()}}).subscribe()}else badge('☁️ Local · sincronización no iniciada')}catch(e){badge('📴 Modo local')}})();
})();